spring.application.name=la-brasa-viva

# ==========================================
# Persistencia Relacional (SQL - H2 Database)
# ==========================================
spring.datasource.url=jdbc:h2:mem:labrasavivadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console Web (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# Persistencia NoSQL (MongoDB - Auditoría y Eventos)
# ==========================================
# Configura tu URI de Atlas con la variable de entorno MONGODB_URI o reemplázala aquí
spring.data.mongodb.uri=mongodb://admin_restaurante:BrasaViva2026@ac-uwauwxx-shard-00-00.mbx5er3.mongodb.net:27017,ac-uwauwxx-shard-00-01.mbx5er3.mongodb.net:27017,ac-uwauwxx-shard-00-02.mbx5er3.mongodb.net:27017/la_brasa_viva?ssl=true&replicaSet=atlas-efhr2y-shard-0&authSource=admin&appName=LaBrasaViva
# Tiempo límite para evitar bloqueos en el arranque si no hay conexión a internet inmediata
spring.data.mongodb.auto-index-creation=true
